import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header'

const Home: NextPage = () => {
  return (
    <div className=''>
      <Head>
        <title>Home </title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header></Header>
      <main>
        <section>
        </section>
      </main>
    </div>
  )
}

export default Home
